//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BooksLibrary.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class AspNetUser
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AspNetUser()
        {
            this.AspNetRoles = new HashSet<AspNetRole>();
        }
    
        public string Id { get; set; }
        public string Email { get; set; }
        [Display(Name = "Email был подтвержден")]
        public bool EmailConfirmed { get; set; }
        [Display(Name = "Хэш пароля")]
        public string PasswordHash { get; set; }
        [Display(Name = "Возвращает некоторое значение, которое меняется при каждой смене настроек аутентификации для данного пользователя")]
        public string SecurityStamp { get; set; }
        [Display(Name = "Номер телефона")]
        public string PhoneNumber { get; set; }
        [Display(Name = "Телефонный номер был подтвержден")]
        public bool PhoneNumberConfirmed { get; set; }
        [Display(Name = "Для данного пользователя включена двухфакторная авторизация")]
        public bool TwoFactorEnabled { get; set; }
        public Nullable<System.DateTime> LockoutEndDateUtc { get; set; }
        public bool LockoutEnabled { get; set; }
        [Display(Name = "Число попыток неудачного входа в систему")]
        public int AccessFailedCount { get; set; }
        [Display(Name = "Ник пользователя")]
        public string UserName { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AspNetRole> AspNetRoles { get; set; }
    }
}
