//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BooksLibrary.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Book
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Book()
        {
            this.Instances = new HashSet<Instance>();
            this.Knowledges = new HashSet<Knowledge>();
        }
    
        public string ISBN { get; set; }
        public string author { get; set; }
        public string name { get; set; }
        public string publication_type { get; set; }
        public Nullable<short> tome { get; set; }
        public string compiler { get; set; }
        public string language { get; set; }
        public string translator { get; set; }
        public string place_publication { get; set; }
        public string publishing { get; set; }
        public Nullable<int> year { get; set; }
        public Nullable<short> number { get; set; }
        public decimal price { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Instance> Instances { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Knowledge> Knowledges { get; set; }
    }
}
