//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BooksLibrary.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Debtor
    {
        public string last_name { get; set; }
        public string name { get; set; }
        public string middle_name { get; set; }
        public string phone { get; set; }
        public Nullable<int> count_days { get; set; }
    }
}
